### ISSUE TITLE
GetConnectionString() on the Limpet

### ISSUE THREAD

**Issue by riccardobecker** [ms-iot/security#10]
Hi there,

we are using the TPM on Iot Core to connect to the iot hub. Configuration works fine, creating a deviceClient also works fine. I am able to send and receive message but after 5 minutes an exception is thrown. It seems that the SasToken expires on that the server side kills the amqp connection.

I also noticed that the GetConnectionString() ignores the validityTime parameter so it always expires after 5 minutes now.

How is this designed to work? The token should be refreshed automatically when it expires I guess?

Thanks in advance!

Riccardo Becker

**Comment by LordOfDorks** [comment]
juunas11 identified the root issue (me not being able to do math) and has provided a fix for the code.

Thank you
S.

**Comment by mms-** [comment]
Please publish a Nuget update!

**Comment by saraclay** [comment]
Closing this issue out for now. If you'd like to file an issue in the future, please do so at: www.github.com/MicrosoftDocs/windows-iotcore-docs
