### ISSUE TITLE
TpmDevice.GetSASToken unused validity parameter

### ISSUE THREAD

**Issue by juunas11** [ms-iot/security#11]
I'm a little bit confused why the GetSASToken function never uses the validity parameter passed in to it?

https://github.com/ms-iot/security/blob/master/Limpet/Limpet.NET/Limpet.cs#L303

Shouldn't it be added to the UNIX epoch expiration time?

**Comment by ooeygui** [comment]
I believe this was fixed by your pull request. Thank you!!!
