### ISSUE TITLE
Several issues when compiling to native/building package

### ISSUE THREAD

**Issue by jpiaggio** [ms-iot/security#13]
I used this library for while now, and in debug mode worked perfect, I was able to connect to authenticate and connect to Azure Services.

Once I tried to release or create a package issues start to poped up:
ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'ExecuteCommand!tpm.dll' in assembly 'TSS.UWP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.		
Error		at SerializationAssemblyGenerator.Program.AddKnownContractsLists(McgCodeTypeDeclaration container, ContractTables tables)				
Error		at SerializationAssemblyGenerator.Program.GenerateDataContractSerializerHelper(IEnumerable`1 contracts, IEnumerable`1 jsonContracts, GeneratorSettings settings, String intermediateAssembly, IEnumerable`1 wcfSerializers)				
Error		at SerializationAssemblyGenerator.Program.GenerateDataContractSerializerHelperCode(IEnumerable`1 contracts, IEnumerable`1 jsonContracts, IEnumerable`1 wcfSerializers)				
Error		at SerializationAssemblyGenerator.Program.Main(String[] args)				
Error		at System.Collections.Generic.Dictionary`2.get_Item(TKey key)	

Thanks in advance!

**Comment by IoTGirl** [comment]
Hi @jpiaggio ,
Apologies for the delay. I have been unable to find a response for you on the IoT Core Team.  Have you reached out to Azure for assistance on the connection?
Sincerely,
IoTGirl

**Comment by MelbourneDeveloper** [comment]
I'm getting these same errors when trying to compile for x86 with .NET Native tool chain.

**Comment by LordOfDorks** [comment]
This preliminary library is going to be discontinued in favor of the TPM based implementation that is shipping in the Azure client library package that will also support the Zero Touch Provisioning service to automatically and securely enroll devices for an IoT Hub based on the TPM Endorsement key.
