### ISSUE TITLE
Only P7 Embedded signatures are supported with Digest Signing

### ISSUE THREAD

**Issue by blizzard4591** [ms-iot/security#15]
I tried to use the CertGen/MakeSB.ps1 script to generate SecureBoot keys, but signing the Signature Lists is failing:

> Done Adding Additional Store
SignTool Error: Only P7 Embedded signatures are supported with Digest Signing.
SignTool Error: An unexpected internal error has occurred.
Error information: "Only Embedded P7 signatures are supported for Digest Signing" (-2147024809/0x80070057)

This happens on a Windows 10 x64 system with the Windows 10 SDK installed, i.e. signtool has version 10.0.14393.33.
Is there a work-around?

**Comment by IoTGirl** [comment]
Hi Blizzard4591,
Have you given this feedback through the Feedback tool?  
Sincerely,
IoTGirl

**Comment by IoTGirl** [comment]
Hi Stefan,
Would you mind taking a look at this issue?
Sincere thanks!
IoTGirl

**Comment by blizzard4591** [comment]
No, I have not used the Feedback-Tool (I guess you are referring to the Windows 10 Feedback-Tool?) - what would be the most appropriate place?

**Comment by merzink** [comment]
Hi Blizzard4591,

The issue with signtool was identified and has been fixed.  The official SDK with the fix will release with the Windows 10 Creator's Update but the latest preview SDK should also have the fix (available via https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewSDK).  Alternatively, you can try using the Win8.1 SDK if that's easier.

Hope that helps.

Cheers,
Merzin

**Comment by IoTGirl** [comment]
Hi Blizzard4591,
Can you please confirm Merzin's response and reopen if you still see this issue? For the future, the Feedback tool creates issues that get routed directly to the feature owner within Microsoft so if your issue is with a Windows component rather than sample code, that is usually the best method to let Microsoft know about it.
Sincerely,
IoTGirl
