### ISSUE TITLE
Could you post a new version of Microsoft.Devices.Tpm on NuGet?

### ISSUE THREAD

**Issue by juunas11** [ms-iot/security#16]
When could we see a new version on NuGet? The expiry parameter is still ignored on 1.0.0 of Microsoft.Devices.Tpm.

**Comment by IoTGirl** [comment]
Hi Stefan,
Can you review this request?
Sincere thanks,
IoTGirl

**Comment by LordOfDorks** [comment]
Dennis is working on a new release as we speak.

**Comment by LordOfDorks** [comment]
@DMattoon is working on a new release as we speak.

**Comment by juunas11** [comment]
Any updates on this? It's been over a month and still I run my demos with a custom build of the library embedded in the project since otherwise it just crashes after 5 minutes.

**Comment by mms-** [comment]
?

**Comment by saraclay** [comment]
Closing this issue out for now. If you'd like to file an issue in the future, please do so at: www.github.com/MicrosoftDocs/windows-iotcore-docs
