### ISSUE TITLE
signtool.exe : fatal error : Signing failed with 1 on -testonly

### ISSUE THREAD

**Issue by anthonws** [ms-iot/security#22]
Cannot run the Turnkey security packages, using the default template for QCB xml.

**Error message:**

"PS C:\iotsec\TurnkeySecurity> Import-Module .\IotDeviceGuardSecureBoot.psm1
PS C:\iotsec\TurnkeySecurity> New-IoTSecureBootPackage -ConfigFileName .\QCDB_settings.xml
(....)
Running SPkgGen.exe C:\iotsec\TurnkeySecurity\QCDB\Output\SecureBoot\Security.SecureBoot.pkg.xml /config:"C:\Program Files (x86)\Windows Kits\10\\Tools\bin\i386\pkggen.cfg.xml" /output:C:\iotse
c\TurnkeySecurity\QCDB\PackageOutput /build:fre /cpu:ARM /variables:_RELEASEDIR=C:\iotsec\TurnkeySecurity\QCDB\PackageOutput;OemName=OEM;BUILD_OS_VERSION=10.0.1.0 /toolPaths:%RazzleToolPath%\x8
6 /nohives /version:10.0.1.0 /spkgsout:C:\Users\anvascon\AppData\Local\Temp\tmp357D.tmp
**--Stack Trace--
   at Microsoft.CompPlat.PkgBldr.Base.Run.RunSPkgGen(List`1 pkgGenArgs, Boolean inWindows, IDeploymentLogger logger, PkgBldrCmd pkgBldrArgs, List`1 spkgList)
   at Microsoft.CompPlat.PkgBldr.Program.PkgToCab(Config config, List`1 spkgGenArgs, Boolean testSignOnly)
   at Microsoft.CompPlat.PkgBldr.Program.Main(String[] args)
--End Stack Trace--
Microsoft (C) spkggen 10.0.10011.16384**

(...)

**signtool.exe : fatal error : Signing failed with 1 on -testonly "C:\Users\anvascon\AppData\Local\Temp\jqgfqcw2.doj\fwrb4psk.o2w_content.cat"
Sign.Cmd RC=1**

**fatal error : Failed to create catalog file for package OEM.Security.SecureBoot
fatal error : Security.SecureBoot.pkg.xml: Failed to sign package integrity catalog file
fatal error : Failed to sign package integrity catalog file
fatal error : Failed to sign file C:\Users\anvascon\AppData\Local\Temp\jqgfqcw2.doj\fwrb4psk.o2w_content.cat with options -testonly  exit code 1**

Commmand failed with code: -1
At C:\iotsec\TurnkeySecurity\IoTDeviceGuardUtils.psm1:91 char:13
             throw "Commmand failed with code: $lastexitcode"
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : OperationStopped: (Commmand failed with code: -1:String) [], RuntimeException
     FullyQualifiedErrorId : Commmand failed with code: -1"

**Comment by saraclay** [comment]
Closing this issue out for now. If you'd like to file an issue in the future, please do so at: www.github.com/MicrosoftDocs/windows-iotcore-docs
