### ISSUE TITLE
signtool.exe moved between WinSDK 14393 and 15063; adjust utils.psm1 module to match

### ISSUE THREAD

**Issue by naikrovek** [ms-iot/security#23]
In the Windows SDK 14393, signtool.exe (and many other tools) are located in `$Win10KitsRoot\bin\[arch]\` but in 15063 they have moved to `$Win10KitsRoot\bin\10.0.15063.0\[arch]`

($Win10KitsRoot is C:\Program Files (x86)\Windows Kits\10)

IoTDeviceGuardUtils.psm1 has not been updated to reflect this change.

**Comment by naikrovek** [comment]
Actually, the change should probably be in settings.xml, and the default (line 9) should (in my opinion) be changed for 15063.

**Comment by sukusuma** [comment]
update underway.. 
yes, To make the change flexible, adding other property WindowsSDKVersion in settings.xml and using in 
IoTDeviceGuardUtils.psm1
--

**Comment by sukusuma** [comment]
Done! 
get latest: IoTDeviceGuardUtils.psm1 & Settings.xml ( QCDB_settings.xml )
