### ISSUE TITLE
IoT Hub Auth using a certificate with TPM

### ISSUE THREAD

**Issue by vslepakov** [ms-iot/security#25]
Hi,
I would like to know whether it is possible to authenticate against Azure IoT Hub using a certificate stored in the TPM. One of the examples I saw was using a symmetric key (primary device key), stored in the TPM (only 2.0?) to create an HMAC as part of a SAS Token. 
Another example for using X509 certificates just used the actual certificate's secret directly in code (DeviceAuthenticationWithX509Certificate). In this case the secret is exposed. Is it possible today to use a certificate stored in the TPM similar to the symmetric key as described above? Or am I supposed to implement custom authentication or wait for the release of the Device Provisioning Service (is it even possible to meet my requirement with it?)

Thanks and best regards!

**Comment by mms-** [comment]
Looks like this is coming, seems to be part of the insider release.

**Comment by saraclay** [comment]
Closing this issue out for now. If you'd like to file an issue in the future, please do so at: www.github.com/MicrosoftDocs/windows-iotcore-docs
