### ISSUE TITLE
Missing Samples link

### ISSUE THREAD

**Issue by TerrenceHenry** [ms-iot/security#28]
The readme file says:

> Please download, build, deploy, and contribute!! For more information and descriptions about the samples found here, see the samples tab here.

The link is broken
http://ms-iot.github.io/content/en-US/win10/StartCoding.htm

**Comment by saraclay** [comment]
Closing this issue out for now. If you'd like to file an issue in the future, please do so at: www.github.com/MicrosoftDocs/windows-iotcore-docs
