### ISSUE TITLE
TPM settings are not readable after Fall Creators Update (10.0.16299.19)

### ISSUE THREAD

**Issue by mpoeckl** [ms-iot/security#29]
After updating Windows 10 IoT Core to version 10.0.16299.19 the (Software) TPM (sTMP) is not working properly.

1. After the upgrade the previously stored TPM settings where not readable from an UWP using C# library.
2. New TPM settings via the Windows 10 IoT Core Device Portal seems to be stored correctly (at least the settings are shown in the IOT Device Portal Web GUI)
3. TPM Settings are still not readable through the most recent C# SDKs using the Microsoft.Devices.Tpm Class. All Libraries are on the most recent versions (Microsoft.NETCore.UniversalWindowsPlatform - 6.0.1, Microsoft.Devices.Tpm - 1.0.0). There is no error thrown but the Device ID (GetDeviceId) shows a random ID/GUID and all other settings (SASToken, HostName...) are returned as empty strings
3. Resetting the TPM settings or using different sTPM Slots did not solve the issue

**Comment by jewendt** [comment]
Did anyone hear any updates on this?  As far as I can tell, all the versions are still having this issue??

**Comment by naikrovek** [comment]
Enable the 'System Management' capability in your visual studio project.

**Comment by mpoeckl** [comment]
As @naikrovek wrote: this issue is related to changes of what an app is allowed to do in Windows 10 IoT Core. You need to define/specify the according capabilities in the app's package manifest. Just open the "Package.appxmanifest" file of your UWP project and edit the "Capabilities" (or open the projects properties page and click on "Package Manifest...").
