### ISSUE TITLE
using NationZ TPM on DragonBoard 410c 

### ISSUE THREAD

**Issue by LeonardBae** [ms-iot/security#30]
Hi,
I am currently testing IoT Hub security via dTPM.
But there is one problem.
When using RP3 and MBM NationZ's TPM, the TPM works normally but it does not seem to work in DragonBoard 410c anymore.
Is there any way to disable fTPM in DragonBoard and use dTPM(NationZ)?

**Comment by saraclay** [comment]
Closing this issue out for now. If you'd like to file an issue in the future, please do so at: www.github.com/MicrosoftDocs/windows-iotcore-docs
