### ISSUE TITLE
Certificates expired

### ISSUE THREAD

**Issue by bibble235** [ms-iot/security#31]
When I run

 New-IotDeviceGuardPackage -ConfigFileName .\settings.xml

signtool.exe sign /v /a /s my /i "Windows Phone Intermediate 2013" /n "Windows Phone OEM Test Cert 2013 (TEST ONLY)" /fd SHA256  /t http://timestamp.verisign.com/scripts/timestamp.dll   "c:\tmp\slmuw5kt.h3q\oj30ey53.xij_content.cat"
signtool.exe : fatal error : Signing failed with 1 on -testonly "c:\tmp\slmuw5kt.h3q\oj30ey53.xij_content.cat"

I believe the reason to be the expiry date is 10/04/2018 which is the 10 April 2018 over here.

Can I generate by own certificates or get new ones? 

Also it would be useful to understand where the "Windows Phone Intermediate 2013" is configured. I have search the source with no success

Thanks

**Comment by parameshbabu** [comment]
Fixed with the PR : Fixing pkg bld error due to expired certs #32

**Comment by bibble235** [comment]
I will test this fix when time permits :) however my workaround was to change the certificates to use 2017 test certs 

C:\Program Files (x86)\Windows Kits\10\tools\bin\i386\sign.cmd 

`set SIGNTOOL_OEM_SIGN=/a /s my /i "Windows Phone Intermediate 2013" /n "Windows Phone OEM Test Cert 2013 (TEST ONLY)" /fd SHA256
`
to
`set SIGNTOOL_OEM_SIGN=/a /s my /i "Windows OEM Intermediate 2017" /n "Windows OEM Test Cert 2017 (TEST ONLY)" /fd SHA256`

And

`if "%CERTIFICATEFLAG%"=="pkg" set CERTIFICATE=/s my /i "Windows Phone Intermediate 2013" /n "Windows Phone OEM Test Cert 2013 (TEST ONLY)" /fd SHA256`

to 

`if "%CERTIFICATEFLAG%"=="pkg" set CERTIFICATE=/s my /i "Windows OEM Intermediate 2017" /n "Windows OEM Test Cert 2017 (TEST ONLY)" /fd SHA256`

All this did result in the process completing we have found our TPM 2.0 on the minnowboard is not valid for use. see [(https://social.msdn.microsoft.com/Forums/vstudio/en-US/5e04e461-768e-4e79-88ec-56e3ceb4c68f/tpm-how-to-enable?forum=WindowsIoT)]

Is there somewhere to find a list of valid TPMs which work with IoT?

**Comment by saraclay** [comment]
Closing this issue out for now. If you'd like to file an issue in the future, please do so at: www.github.com/MicrosoftDocs/windows-iotcore-docs
