### ISSUE TITLE
PowerShell commands to security the OS

### ISSUE THREAD

**Issue by deepgray** [ms-iot/security#33]
are there any other capabilities to security the OS other than hardware (TPM,etc.)?

**Comment by saraclay** [comment]
Hi @deepgray - we have a few docs that you could start with here: https://docs.microsoft.com/en-us/windows/iot-core/secure-your-device/buildingsecuredevices

Not sure if I understood your question exactly, but I hope this helps. If you have any future issues, please file them at: www.github.com/MicrosoftDocs/windows-iotcore-docs
